name: Maven Build and Publish
on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: adopt

    - name: Build with Maven
      run: mvn clean package
      
    - name: ls 
      run: ls -al target

    - name: Jfrog push v2
      uses: jfrog/setup-jfrog-cli@v2
      env:
        JF_URL: http://3.133.134.67:8081
        JF_USER: admin
        JF_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
    - run: |
        jf rt u "target/*.jar" "jfrog/github-action-maven-tutorial/app.jar"

    - name: Log in to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/javaapp:v1
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Deploy to Server
      run: |
        ssh ubuntu@18.222.137.144 
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/javaapp:v1 &&
          docker stop java-app &&
          docker rm java-app &&
          docker run -d --name java-app ${{ secrets.DOCKERHUB_USERNAME }}/javapp:v1
        "

